### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#150]
Okay so i have the project building with JDK on my machine. I was hoping i could somehow just build in docker and extract an interface but it puts in the user hots interface folder so thats fine. 

Few things I want to do but im struggling:

- you have an option to remove player names on the hero, how can i replace player name with hero name?
- on the loading screen there are player names, can i remove those but keep the Hero name?
- remove the text notifications completely (also means I avoid the NOTIFICATION TEXT bug)
-  get player names out of the UI and remove the bottom left player portrait and talents

I looked around in the UI and found

`<Frame type="HeroContainerFrame" name="HeroContainerFrame">` 

But when I try to modify this or set <Visible val="false"/> and rebuild the interface, it doesnt seem to do anything so maybe I misunderstand what I can or cannot change in the files.

I refactored my auto spectator and wanted to launch it with the refactoring but only once I get the Interface working how I want for a 24/7 twitch stream.

**Comment by Ahli** [comment]
> you have an option to remove player names on the hero, how can i replace player name with hero name?
That can be done via editing the properties of the UnitStatusName within each unit status via bindings: NameType needs to become "Unit" and UseNameTypeVisibilityRules must be false.

> on the loading screen there are player names, can i remove those but keep the Hero name?
I assume that you cannot edit the loading screen. I never tried, but the Observer Interface should be loaded last.

> remove the text notifications completely (also means I avoid the NOTIFICATION TEXT bug)
Hiding the GameNotificationsPanel should be enough for that. Maybe it needs to be moved offscreen.

> get player names out of the UI and remove the bottom left player portrait and talents
I made a hotkey for that. But I am currently still showing the behavior bar instead. Could be made modifiable via a setting.

Wouldn't it be easier to integrate these settings as settings features into AhliObs and then use my settings editor to adjust it?

**Comment by pjmagee** [comment]
I think thats perfectly fine to do yes. Im just struggling to do it myself. I tried to make changes and even comment out entire sections but then the game still shows them so its almost like it didnt actually do what I  thought.

**Comment by Ahli** [comment]
- The loading screens are not editable because the layouts are locked. I tried editing the text style used, but those changes did not persist between replays. Thus, loading screens cannot be altered.
- I have added a setting that allows forcing the name on the status bar to be the hero name or the player name instead of an automatic selection (hero for AI, player for human)

@pjmagee, do player names need to be removed from the Dialog opening on TAB (Leaderpanel) or is it enough to remove them from above the health bars?

**Comment by pjmagee** [comment]
I never use the Tab feature, so not needed. One concern was just player names really. I know battlenet has # after so its not exactly easy for someone to message a player which is why I wasnt extremely concerned. but i certainly want to make sure people watching replays refer to the characters compared to the players. Maybe i can come up with some OCR long term that only puts the game stream on once the timer is being detected by the OCR.

**Comment by pjmagee** [comment]
Also super big thanks for including these!! I'm reading your recent commit to learn too. I'd love to contribute as well.

**Comment by Ahli** [comment]
Do you need to hide the chat, too? Those include player names, too.

**Comment by pjmagee** [comment]
> Do you need to hide the chat, too? Those include player names, too.

I was going to want to hide that too, since it can have all kinds of stuff in it. And in reality, its not relevant to the game. Plus its unmoderated so probably best to entirely remove it.

**Comment by Ahli** [comment]
I am nearly done implementing changes for the settings editor to properly support number, boolean and predefined choices.

**Comment by pjmagee** [comment]
Btw the way, I did download the interface editor, i see it starts up with a batch file and uses an isolated version of java to run but for some reason it was crashing on me. Not sure why. Does the latest install still work?

**Comment by Ahli** [comment]
I fixed a bug, so potentially not :D

**Comment by pjmagee** [comment]
Errm, just to clarify so im not confused all the following can be disabled by default without needing to modify UI toggles during game?

- chat hidden before game loads
- bottom left hero talents + picture/abilities hidden before game loads
- hero name instead of player name
- top notifications disabled before game loads
- bottom timer/controls hidden before game loads

**Comment by pjmagee** [comment]
Just so i know if i need to keep automation on modifying game controls whe na replay loads or not.

**Comment by pjmagee** [comment]
Right now im having to do this to the UI   (Zoom is probably understandable)

```
private async Task ConfigureLoopAsync()
        {
            while (State != State.End)
            {
                try
                {
                    if (State == State.Running)
                    {
                        if (!ClientConfiguredChat()) HideChat();

                        await Task.Delay(500);

                        if (!ClientConfiguredControls()) HideControls();

                        await Task.Delay(500);

                        if (!ClientConfiguredUnitPanel()) ConfigureUnitPanel();

                        await Task.Delay(500);

                        if (!ClientConfiguredZoom()) ConfigureZoom();

                        await Task.Delay(500);

                        if (!ClientFollowModeSet()) ConfigureFollowMode();

                        await Task.Delay(500);

                    }

                    var configured = new[] { ClientConfiguredChat(), ClientConfiguredControls(), ClientConfiguredZoom(), ClientFollowModeSet(), ClientConfiguredUnitPanel() }.All(configured => configured == true);

                    if (configured)
                    {
                        logger.LogInformation("Client configured.");
                        return;
                    }
                }
                catch (Exception e)
                {
                    logger.LogError(e, "Could not complete configure loop");
                }

                await Task.Delay(1000);
            }
        }
```

**Comment by Ahli** [comment]
> Errm, just to clarify so im not confused all the following can be disabled by default without needing to modify UI toggles during game?
> 
> * chat hidden before game loads
setting for initial state added; Set **ChatInitiallyHidden** to **true**

> * bottom left hero talents + picture/abilities hidden before game loads
setting for initial state added; additional behavior bar removed
=> Set **SelectedUnitInfoInitiallyHidden** to **true**

> * hero name instead of player name
setting added: Set **HeroUnitStatusNameType** to **Unit**

> * top notifications disabled before game loads
setting added: Set **GameNotificationsPanelVisible** to **false**

> * bottom timer/controls hidden before game loads
TODO

**Comment by Ahli** [comment]
@pjmagee, I now have implemented all of your requested settings.

Do you have further requests?

**Comment by pjmagee** [comment]
> @pjmagee, I now have implemented all of your requested settings.
> 
> Do you have further requests?

Nothing that I can think of. I was reading some twitter requests and there seem to be many cool ones. The fountain tap one seems the most wanted? 

We can close this ticket.
