### ISSUE TITLE
Ragnaros Image showing on Dragon Knight HP

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#154]
https://clips.twitch.tv/BovineBumblingJalapenoPermaSmug

**Comment by Ahli** [comment]
Because he entered the Dragon Knight and added an image there to show who controls it.

**Comment by pjmagee** [comment]
AHHHH.

**Comment by pjmagee** [comment]
Now i feel dumb...

**Comment by pjmagee** [comment]
I'm Closing this and pretend i didnt say anything.
