### ISSUE TITLE
Strange request regarding the Timer Size/Location/Colour

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#155]
Hey Ahli, how hard would it be to produce something like this? 

My OCR timer has been having a lot of false positives and also tends to not pick up any text, the OCR is using Native Windows OCR but im just wondering if it could be more stable with something like the following:

[![](https://i.imgur.com/7txxr7B.png)]

**Comment by Ahli** [comment]
I could do that as a setting, but that will look odd in a stream.

Maybe tweaking the label slightly already improves it. Can you give me a simple app to test the OCR or can I use Heroesreplay for that already?
Maybe I can tweak the appearance only slightly and improve the detection rate, e.g. via adding an outline. For that, I need to be able to test.

**Comment by pjmagee** [comment]
I think right now I have a few issues, detection rate is better when i scale the image up so its not happening as much but another issue i am having is sometimes the process will get stuck in a loop and not kill the game - thats just bad logic on my end. I'm currently re-writing the start/running/end logic of the spectator so once a timer is no longer found, it will just kill the game. 

I found my current way is good for like 90% of the games, but there are odd times where for some reason it just does not think the core dies 10+ seconds from the current timer so there is some weird replay internal timer and offset timer issues and im not sure if its to do with the 16 frames per second or game loops. But my new way should hopefully help reduce this problem.

IF i think the state detection is still not good enough in its current state, maybe I can help on making something work a bit better. Can we keep this issue open for now? I would like to come back to it at some point.

**Comment by Ahli** [comment]
> Can we keep this issue open for now? I would like to come back to it at some point.

sure

> but there are odd times where for some reason it just does not think the core dies 10+ seconds from the current timer so there is some weird replay internal timer and offset timer issues and im not sure if its to do with the 16 frames per second or game loops

I can't follow

> The reason why I cannot just use the "game Length" information in a replay is, sometimes - a replay is upto even 15minutes longer than the END of the game, because people stay at the MVP screen and dont exit, so having it run until the full length of the replay would be horrible for 20%-30% of the games.

That's very unfortunate.

**Comment by pjmagee** [comment]
For some reason, in certain games. When I check the timer and then compare it to the time the Core should die, the condition fails. Almost like the internal replay timer does not match up to the offset timer used in the UI. The replay does not know about the -30:00 second start time. 

`(timer.Value.Seconds + gameLoopsOffset) / gameLoopsPerSecond` could be something to do with it. I'm not entirely sure. But i think ive figured out a better solution anyway. :)

**Comment by pjmagee** [comment]
I fixed most of the issues now with the OCR. Sometimes it saw '.' instead of ':' or mixed up some numbers for letters. I just do some sanitization once i recieve the Text from the OCR.
