### ISSUE TITLE
Cho'Gal Unit Name shows as Player Names

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#170]
So I have the Unit name display type enabled but the UI is still showing the Player names. Seems like this an engine bug and not something we can control?

**Comment by Ahli** [comment]
Nice catch! I have not thought of Cho'Gall!

The label will most likely be overridden after the game started.
Potentially, it needs to use a different label.

**Comment by pjmagee** [comment]
I noticed it during my spectator, It caught a Cho'Gall player called Cov'id19 and I was laughing and then I was like "hey, wait a second!!".
