### ISSUE TITLE
[Questions] Hey dude, again im back. Not about a bug. I'm abusing the issue system.

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#73]
Ive gone through a large portion of your work to understand the structure of a .StormInterface file and how its packaged. The reason for this is I am wanting to remove or add certain overlays.

With the behaviour of my software, some things are not needed, somethings could be tweaked or enlarged for OCR usage. So I have a few questions!

1) Do you know if there is a built in way to remove the observer/replay controls panel in the bottom left corner by configuration, or must I toggle to hide it with the hotkey? 

I would rather not go down the route of toggling the controls every replay, and so I wondered if there was a way to either a) entirely remove this XML layer and it wont break the game? or have the observer controls in a state where they are default to hidden state?

2) I see where the top game timer is, but im not sure if there is a way to maybe increase the size of the timer and change the background/foreground color of the text of the timer? this would make my software work better on different size/resolutions of the game running without causing my OCR  timer recognition code to become unstable on smaller resolutions.

**Comment by Ahli** [comment]
1: The game sets the initial state of the replay controls. It should be possible to add code to hide them at the start based on a setting in the interface.

2. This is controlled by the "style" the timer's label uses.

**Comment by pjmagee** [comment]
Thanks for the information. I think i may get myself a dev enviornment setup and play around with the UI myself. I'm at the stage where my auto spectator tool is almost ready for production use. I ran a test stream not long ago which was pulling replay files from the HotsAPI database from S3 and it worked great. A few minor things need to be fixed and also finding a steady cloud platform with a GPU instance is also something I need to investigate (if its too costly, i may run this 24/7 in-house).

Would like to make a few adjustments to the StormInterface.

**Comment by Ahli** [comment]
I fixed an issue when you are using the interfacebuilder fresh (cache directory was not created).

If you encounter issues or have handling wishes, let me know.
You only need Java 13 in your path variables (or you edit **/dev/debugCompile.bat** to use a different version providing a full path).

There are three ways to use the builder:
* build via GUI
* via commandline:
** start it manually and keep it open to skip the booting process (commandline will send a signal to the GUI's process and it builds there. Output is transferred back. Communication is done via a socket.)
** the builder starts, builds and closes itself, if there was no error

I will probably experiment with JDK 14's records, soon., though. This project is still my Java tech playground.

**Comment by pjmagee** [comment]
This is an old issue raised about how i open the project. Gonna close it so we dont make too much noise in the issues.
